"""add invoice_sequence table and payment indexes

Revision ID: 45adcde5bb5b
Revises: b3c4d5e6f7a8
Create Date: 2026-03-11 15:42:03.430313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45adcde5bb5b'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.String(length=8), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('barcode_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Code128, EAN13, UPCA',
               existing_nullable=True)
        batch_op.alter_column('barcode_source',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='generated, manual, supplier',
               existing_nullable=True)

    # Performance indexes: dashboard and reporting queries filter/group on these columns
    op.create_index('ix_payment_created_at', 'payment', ['created_at'])
    op.create_index('ix_sale_invoice_status_customer', 'sale', ['invoice_status', 'customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_invoice_status_customer', 'sale')
    op.drop_index('ix_payment_created_at', 'payment')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('barcode_source',
               existing_type=mysql.VARCHAR(length=20),
               comment='generated, manual, supplier',
               existing_nullable=True)
        batch_op.alter_column('barcode_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='Code128, EAN13, UPCA',
               existing_nullable=True)

    op.drop_table('invoice_sequence')
    # ### end Alembic commands ###
