"""Add image_filename to Product

Revision ID: b9dd57ac09d8
Revises: 75f0a284fd55
Create Date: 2026-02-26 17:13:20.928251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9dd57ac09d8'
down_revision = '75f0a284fd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sale_id'), ['sale_id'], unique=False)
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('sale_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RETAIL', 'WHOLESALE', 'MIXED', name='saletype'),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))
        batch_op.alter_column('amount_due',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('invoice_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PAID', 'PARTIAL', 'UNPAID', 'VOID', name='invoicestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'"))
        batch_op.create_index(batch_op.f('ix_sale_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('price_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RETAIL', 'WHOLESALE', name='pricetype'),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('price_type',
               existing_type=sa.Enum('RETAIL', 'WHOLESALE', name='pricetype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_sale_customer_id'))
        batch_op.alter_column('invoice_status',
               existing_type=sa.Enum('PAID', 'PARTIAL', 'UNPAID', 'VOID', name='invoicestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'"))
        batch_op.alter_column('amount_due',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('sale_type',
               existing_type=sa.Enum('RETAIL', 'WHOLESALE', 'MIXED', name='saletype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payment_customer_id'))

    # ### end Alembic commands ###
