"""Add returns and voids

Revision ID: d24fff74d40a
Revises: b9dd57ac09d8
Create Date: 2026-02-27 19:20:17.942124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd24fff74d40a'
down_revision = 'b9dd57ac09d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Update sale_status ENUM to include new values (Alembic doesn't auto-detect enum changes)
    # IMPORTANT: Use Python enum NAMES (COMPLETED, PARTIALLY_RETURNED, etc.), NOT display values
    # SQLAlchemy stores enum member names by default, not .value strings
    op.execute("ALTER TABLE sale MODIFY COLUMN sale_status ENUM('COMPLETED','PARTIALLY_RETURNED','REFUNDED','VOIDED') DEFAULT 'COMPLETED'")

    op.create_table('return_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_no', sa.String(length=20), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('return_type', sa.Enum('RETURN_ONLY', 'RETURN_AND_REFUND', name='returntype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'REVERSED', name='returnstatus'), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_method', sa.Enum('CASH', 'CARD', 'E_DAHAB', 'ZAAD', 'STORE_CREDIT', 'MOBILE_MONEY', name='paymentmethod'), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_transaction_return_no'), ['return_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_return_transaction_sale_id'), ['sale_id'], unique=False)

    op.create_table('void_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('voided_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('void_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_void_transaction_sale_id'), ['sale_id'], unique=True)

    op.create_table('return_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('unit_price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['return_transaction.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sale_id'), ['sale_id'], unique=False)
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('sale_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RETAIL', 'WHOLESALE', 'MIXED', name='saletype'),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))
        batch_op.alter_column('amount_due',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('invoice_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PAID', 'PARTIAL', 'UNPAID', 'VOID', name='invoicestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'"))
        batch_op.create_index(batch_op.f('ix_sale_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('price_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RETAIL', 'WHOLESALE', name='pricetype'),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('price_type',
               existing_type=sa.Enum('RETAIL', 'WHOLESALE', name='pricetype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_sale_customer_id'))
        batch_op.alter_column('invoice_status',
               existing_type=sa.Enum('PAID', 'PARTIAL', 'UNPAID', 'VOID', name='invoicestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'"))
        batch_op.alter_column('amount_due',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('sale_type',
               existing_type=sa.Enum('RETAIL', 'WHOLESALE', 'MIXED', name='saletype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'RETAIL'"))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payment_customer_id'))

    op.drop_table('return_item')
    with op.batch_alter_table('void_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_void_transaction_sale_id'))

    op.drop_table('void_transaction')
    with op.batch_alter_table('return_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_transaction_sale_id'))
        batch_op.drop_index(batch_op.f('ix_return_transaction_return_no'))
        batch_op.drop_index(batch_op.f('ix_return_transaction_created_at'))

    op.drop_table('return_transaction')
    # ### end Alembic commands ###
